services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minikanban_net


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      container_name: api
      restart: always
      depends_on:
        - db
      ports:
        - "${API_PORT}:3000"
      volumes:
        - ./api:/usr/src/app
        - /usr/src/app/node_modules
      env_file:
        - .env
      networks:
        - minikanban_net

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/usr/src/app 
      - /usr/src/app/node_modules
    networks:
      - minikanban_net

networks:
  minikanban-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local